apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-kompose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: owncloud
  name: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: owncloud
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-kompose.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: owncloud
    spec:
      containers:
        - image: owncloud
          name: owncloud
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
